spring:
  profiles:
    active: mock
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    password: postgres
    username: postgres
    schema: classpath:/sql/schema.sql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
baseBackendUrl: http://localhost:8080

---

spring:
  profiles:
    active: database
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    password: postgres
    username: postgres
    schema: classpath:/sql/schema.sql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
baseBackendUrl: http://localhost:8080